apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-electronics:aca10f0677550d20d6ad4e54f086ce4ff0b471b3
        ports:
        - containerPort: 80
