apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-main:fc69c5c2f2c11967bc3ceca1eab41c23357ea786
        ports:
        - containerPort: 80
