apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:16ef420c3f4a2dd766e3441dc816e5c25037f88e
        ports:
        - containerPort: 80
