apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:8832b0334473d3a7057130b5a70edda3609dbef1
        ports:
        - containerPort: 80
