apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 049061799945.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:20d814df7e0d514936f2113368240de7ebb819a3
        ports:
        - containerPort: 80
